### ISSUE TITLE
missing src/lib folder -- maybe add a warning at the top of the Readme?

### ISSUE THREAD

**Issue by jdar** [SilentCicero/ethdeploy#4]
It appears that src/index.js references './lib/index.js' which does not exist. 

It is fine that the project is not mature, but maybe you could put a warning on the README, for now?

**Comment by SilentCicero** [comment]
@jdar so the ethdeploy module is ready for use, I can put a warning that it is in Alpha though, good call. As for the lib/index.js I'll look into that.

How did you get that error, can you provide more information? The `lib` folder is generated at build time. Just run `npm run build` if you are building from source.

**Comment by jdar** [comment]
Hi Nick,

Thanks in advance. I do like the approach you are taking, so I appreciate your help onboarding.

Here are some logs. I hope they help. Let me know if I can be more explicit anywhere.


Short answer:
I get the 'lib/index.js' error when I run 'npm run build' in the ethdeploy/ directory. 

The error I get when I try to run the example/ per the readme is different. Cannot resolve 'meow' although I have installed it in every possible place (-g and local) 

Short logs [gist of more complete logs below]

/home/tulipadmin/ethdeploy/example/index.js
  3:1  warning  Unexpected console statement  no-console

/home/tulipadmin/ethdeploy/src/index.js
  2:21  error  Unable to resolve path to module './lib/index.js'  import/no-unresolved

✖ 2 problems (1 error, 1 warning)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ethdeploy@1.0.6 lint:eslint: `eslint --ignore-path .gitignore --ignore-pattern **/**.min.js "."`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ethdeploy@1.0.6 lint:eslint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
...
[ more on Ubuntu and OSX (logs for Ubuntu 16: https://gist.github.com/jdar/d047d5f98a89016445703faae9200482) ]

After generating those logs, I also upgraded node to 8.1.3, but there was no change.

I do not see a reference to a 'npm run build' in the readme? Perhaps you meant 'npm run deploy'

When in example/, I run 'npm run deploy' :
tulipadmin@tuliplabs:~/ethdeploy/example$ npm run deploy

> ethdeploy-example@1.0.0 deploy /home/tulipadmin/ethdeploy/example
> node ./node_modules/ethdeploy/bin/ethdeploy.js ./ethdeploy.testrpc.config.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'meow'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)

**Comment by SilentCicero** [comment]
Looking into this, `meow` as you can see in the package.json is installed. Not sure why there is a problem. I'm trying a git clone and npm install now. Will see if I can reproduce.

**Comment by SilentCicero** [comment]
Oh, got it @jdar sorry about that. Naming of folders has removed the lib folder in src. That was accidentally pushed to Github. Will patch.

**Comment by SilentCicero** [comment]
Should be patched now. Let me know if you are having other troubles.

**Comment by jdar** [comment]
Hi Nick,

Thank you for tracking down the '/lib' folder thing. That works.

I looked into 'meow' error, and found out a few things. I will add as a separate ticket that has a few minor tweaks, and a description that may point you in the right direction.

Best,
D
